---
- name: Block IP addresses
  hosts: ARUBA
  gather_facts: no
  vars:
    blocked_ip: "0.0.0.0"  # Will be passed dynamically

  tasks:

    - name: ACL IP BLOCK
      community.network.aruba_config:
        lines:
          - "deny ip host {{ blocked_ip }} any"
        parents: "ip access-list extended BLOCK_BAD_IPS"
      when: blocked_ip is defined
