{
 "title": "Netflow SQL",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Source", "label": "src", "query": "mysql" },
   { "name": "Database", "label": "db", "query": "SHOW databases;" }
  ]
 },
 "panels": [
  {
   "title": "Top talkers",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "Netflow_Data",
     "rawSql": "SELECT COUNT(IPV4_SRC_ADDR), IPV4_SRC_ADDR FROM SFlow_Data.data GROUP BY IPV4_SRC_ADDR ORDER BY COUNT(IPV4_SRC_ADDR) DESC "
    }
   ]
  },
  {
   "title": "Top destinations",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "dataset": "Netflow_Data",
     "rawSql": "SELECT COUNT(IPV4_DST_ADDR), IPV4_DST_ADDR FROM SFlow_Data.data GROUP BY IPV4_DST_ADDR ORDER BY COUNT(IPV4_DST_ADDR) DESC "
    }
   ]
  },
  {
   "title": "Top port destinations",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "Netflow_Data",
     "rawSql": "SELECT COUNT(DST_PORT), DST_PORT FROM SFlow_Data.data GROUP BY DST_PORT ORDER BY COUNT(DST_PORT) DESC "
    }
   ]
  },
  {
   "title": "Top source ports",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "dataset": "Netflow_Data",
     "rawSql": "SELECT COUNT(SRC_PORT), SRC_PORT FROM SFlow_Data.data GROUP BY SRC_PORT ORDER BY COUNT(SRC_PORT) DESC "
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "state-timeline",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT SRC_PORT value, DATE time \nFROM SFlow_Data.data\nORDER BY DATE DESC "
    }
   ]
  }
 ]
}