
services:

  mysql_replica:
    image: mysql:latest
    volumes:
      - mysql-replica:/tmp
    command:
      [
        "mysqld",
        "--datadir=/tmp/mysqldata-replica",
        "--log-bin=bin.log",
        "--server-id=2"
      ]
    environment:
      MYSQL_ROOT_PASSWORD: cisco
      MYSQL_DATABASE: replicate
      MYSQL_USER: replicate_user
      MYSQL_PASSWORD: cisco
    ports:
      - "3309:3306"


volumes:
  mysql-replica:

















  #database:
   # image: mysql:latest #9.3.0
    #container_name: database
    #ports:
   #   - "3038:3036"
#    environment:
 #     MYSQL_ROOT_PASSWORD: cisco
  #    MYSQL_DATABASE: database
   #   MYSQL_USER: user
    #  MYSQL_PASSWORD: cisco
#    command:
 #     [
  #      "mysqld",
   #     "--datadir=/var/lib/mysql",
    #    "--log-bin=bin.log",
     #   "--server-id=1"
      #]
#    volumes:
 #     - ./database:/var
  #    - ./database_conf:/etc/mysql/conf.d
   # networks:
    #  - db

#  replicate:
 #   image: mysql:latest #9.3.0
  #  container_name: replicate
   # ports:
    #  - "3039:3036"
#    environment:
 #     MYSQL_ROOT_PASSWORD: cisco
  #    MYSQL_DATABASE: replicate
   #   MYSQL_USER: user
    #  MYSQL_PASSWORD: cisco
#    command:
 #     [
  #      "mysqld",
   #     "--datadir=/var/lib/mysql",
    #    "--log-bin=bin.log",
     #   "--server-id=2"
      #]
#    volumes:
 #     - ./replicate:/var
  #    - ./replicate_conf:/etc/mysql/conf.d
   # networks:
    #  - db




#networks:
 # db:
  #  driver: bridge
