{
 "title": "Netflow SQL",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Source", "label": "src", "query": "mysql" },
   { "name": "Database", "label": "db", "query": "SHOW databases;" }
  ]
 },
 "panels": [
  {
   "title": "Protocols",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "dataset": "Sflow_Data",
     "rawSql": "SELECT \n  DATE AS time,\n  CAST(PROTO AS INT) AS protocol\nFROM \n  Sflow_Data.data\nGROUP BY \n  protocol;"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT CAST(SRC_PORT AS INT) value, DATE time \nFROM Sflow_Data.data\nORDER BY DATE DESC "
    }
   ]
  },
  {
   "title": "Top talkers",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "Netflow_Data",
     "rawSql": "SELECT COUNT(IPV4_SRC_ADDR), IPV4_SRC_ADDR FROM Sflow_Data.data GROUP BY IPV4_SRC_ADDR ORDER BY COUNT(IPV4_SRC_ADDR) DESC "
    }
   ]
  },
  {
   "title": "Top destinations",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "dataset": "Netflow_Data",
     "rawSql": "SELECT COUNT(IPV4_DST_ADDR), IPV4_DST_ADDR FROM Sflow_Data.data GROUP BY IPV4_DST_ADDR ORDER BY COUNT(IPV4_DST_ADDR) DESC "
    }
   ]
  },
  {
   "title": "Top port destinations",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "Netflow_Data",
     "rawSql": "SELECT COUNT(DST_PORT), DST_PORT FROM Sflow_Data.data GROUP BY DST_PORT ORDER BY COUNT(DST_PORT) DESC "
    }
   ]
  },
  {
   "title": "Top source ports",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "dataset": "Netflow_Data",
     "rawSql": "SELECT COUNT(SRC_PORT), SRC_PORT FROM Sflow_Data.data GROUP BY SRC_PORT ORDER BY COUNT(SRC_PORT) DESC "
    }
   ]
  }
 ]
}