---
- name: Block IP addresses
  hosts: # Insert Ip or something
  gather_facts: no
  vars:
    blocked_ip: "0.0.0.0"  # Will be passed dynamically

  tasks:

    - name: Get current ACL
      aruba_command:
        commands:
          - "show running-config | include deny"
      register: aclOutPut

    - name: IP check
      set_fact:
        ip_already_blocked: "{{ aclOutPut.stdout[0] is search('deny .* {{ blocked_ip }}') }}"

    - name: ACL IP BLOCK
      aruba_config:
        lines:
          - "deny ip host {{ blocked_ip }} any"
        parents: "ip access-list extended BLOCK_BAD_IPS"
      when: blocked_ip is defined
