
services:
  mysql_source:
    image: mysql:latest
    volumes:
      - mysql-source:/tmp
    command:
      [
        "mysqld",
        "--datadir=/tmp/mysqldata-source",
        "--log-bin=bin.log",
        "--server-id=1"
      ]
    environment:
      MYSQL_ROOT_PASSWORD: cisco
      MYSQL_DATABASE: source
      MYSQL_USER: source_user
      MYSQL_PASSWORD: cisco
    ports:
      - "3308:3306"


volumes:
  mysql-source:


